### ISSUE TITLE
Testowa baza danych i przyszłość pluginu oraz jakiś randomowy bełkot.

### ISSUE THREAD

**Issue by SlimaKCoder** [Dzikoysk/FunnyGuilds#290]
Tak jak w tytule, potrzebuje testowej bazy danych z graczami i gildiami dla projectQ.

Github: https://github.com/SlimaKCoder/projectQ/tree/Development
Demo: http://pq.whiteteam.eu

**Comment by Wruczek** [comment]
Mogę zhostować pliki i podpiąć pod swoją bazę danych z danymi.

**Comment by SlimaKCoder** [comment]
A dałbyś radę użyczyć kopię bazy Mysql? Kopię możesz wykonać przy pomocy mysqldump: http://designconcept.webdev20.pl/articles/mysqldump-kopia-zapasowa-bazy-danych/

**Comment by Wruczek** [comment]
Ok, ale będę musiał pozmieniać trochę danych w trosce o dobro graczy.
Prześle za około 2 godziny jak będę miał czas :)

**Comment by Wruczek** [comment]
Proszę: http://upload.mcwg.pl/server/php/files/funnyguilds.sql

**Comment by SlimaKCoder** [comment]
Za godzinę lub dwie podepnę i będę testował :) Dzięki <3

**Comment by SlimaKCoder** [comment]
Przy odzyskiwaniu wyrzuca błąd: "ERROR 1068 (42000) at line 1379: Multiple primary key defined".

**Comment by Wruczek** [comment]
Linia o której mowa:
"ALTER TABLE `guilds` ADD PRIMARY KEY (`uuid`);"
Spróbuj usunąć tabele guilds, regions oraz users i zaimportować to ponownie.

**Comment by SlimaKCoder** [comment]
FunnyGuilds nie wspiera prefixów do tabel nie?

**Comment by Wruczek** [comment]
Nie

**Comment by SlimaKCoder** [comment]
Ok, to wiele ułatwia ;D

**Comment by SlimaKCoder** [comment]
Poziom zagmatwania danych w FunnyGuilds to masakra. Zapytania długie na kilometry, ale nie ma nic niemożliwego ;) Myślę, że jeszcze dzisiaj wsparcie dla FunnyGuilds będzie realnie działało w mniejszym lub większym stopniu.

**Comment by Wruczek** [comment]
Tak, w FunnyGuilds dużo rzeczy jest jeszcze do zmienienia, w tym cała struktura baz danych :D Powodzenia!

**Comment by SlimaKCoder** [comment]
FunnyGuilds dopuszcza graczy bez gildii. Właściwie to jest ich całkiem sporo i zastanawiam się co wstawić w pole gildii dla takich graczy? W tej chwili jest puste [], czy lepiej by pisało [Brak] lub Brak czy coś w ten deseń?

**Comment by Wruczek** [comment]
Możesz dać brak, minusa (-) albo (tak jak ja mam): Aktualnie gracz nie posiada gildii

**Comment by Dzikoysk** [comment]
Ta baza była tworzona po jakiś 10 minutach obcowania z mysql i od tamtej pory (tj. jakieś v1.0.5?) nie była ruszana (oprócz dodawania jakiś pojedynczych nowych wartości), więc domyślam się, że kogoś, kto siedzi w tym cały czas mocno to razi :D

**Comment by SlimaKCoder** [comment]
Mocno razi to mało powiedziane ;D Ale dostosowałem projectQ do niej. Może też nie jestem jakoś zaawansowany w MySQL, ale na tyle by wyciągnąć potrzebne dane ;)

**Comment by SlimaKCoder** [comment]
Powinno działać, dodałem sporo poprawek: https://github.com/SlimaKCoder/projectQ/commit/437966ae6161ddaa7921d29c9efac6c307879011
Pobierz sobie najnowszą wersję Dev i przetestuj: https://github.com/SlimaKCoder/projectQ/archive/Development.zip

**Comment by TheMolkaPL** [comment]
Czekam jeszcze na aktualizację http://pq.whiteteam.eu ;) :+1:

**Comment by SlimaKCoder** [comment]
A bo mi się chce to aktualizować xD Od jakiegoś czasu pracuję w szkole i w domu na dysku przenośnym,. Mam na nim wszystko, łącznie z serwerem WWW i lokalnymi domenami, więc nie mam potrzeby używać VPSa ;D Jak chcesz to mogę podesłać Ci stworzoną przeze mnie bazę dla OpenGuild.

**Comment by SlimaKCoder** [comment]
Ok, demo zaktualizowane. Przy okazji zmieniłem motyw, bo tamten się znudził :P Demo korzysta teraz z bazy danych dla FunnyGuilds i wydaje się działać bez zarzutów.

**Comment by TheMolkaPL** [comment]
Steves everywhere ;_____________;

**Comment by Wruczek** [comment]
I cry evrytim wit ju ;__;

**Comment by SlimaKCoder** [comment]
No cóż, w mojej bazie dla OpenGuild wysiliłem się i dodałem tylko UUID, dla których są skiny ;) Natomiast baza dla FunnyGuilds pochodzi z realnego serwera :P

**Comment by SlimaKCoder** [comment]
Wielki odkop! Czy ta baza jest nadal aktualna, były jakieś zmiany w SQL od tamtego czasu?

**Comment by Wruczek** [comment]
Zmian w SQL nie było, Dzikoysk przestał się interesować projektem i z tego co mi wiadomo robi własną grę w Javie i na pluginy do Minecraftów nie ma już czasu.

**Comment by SlimaKCoder** [comment]
Nie dobrze ;/ To ten plugin nadal będzie żył? Planujecie robić coś nowego z Molką czy może jednak będziecie kontynuować za zgodą Dzikosa?

**Comment by Wruczek** [comment]
https://github.com/TheMolkaPL/FunnyGuilds
Molka trochę pozmieniał i zaktualizował do 1.8.
Było 5 aktualizacji i projekt tam także leży nieruszany

**Comment by SlimaKCoder** [comment]
Właśnie. Jak dla mnie można by zabrać kod z FunnyGuilds, potem przerobić całkowicie bazy danych , zaktualizować i poprawić trochę resztę kodu i wypuścić jako FunnyGuilds Reloaded czy coś w ten deseń. Ponad to można by zrobić prosty konwerter ze starej bazy FunnyGuilds na nową. (Ze SQL mogę pomóc, ale na Javie się nie znam ;... Chyba, że nauczycie mnie trochę ;P)

**Comment by Wruczek** [comment]
No właśnie, nikomu się nie chce tego robić
Dodatkowo Minecraft traci na popularności = mniej serwerów = mniejsze zainteresowanie taką wtyczką

**Comment by SlimaKCoder** [comment]
Z tego co mi wiadomo to nadal sporo serwerów korzysta z FunnyGuilds (nawet dużych, np. http://centrumpvp.pl/). Do tego ten plugin można by rozreklamować nie tylko na mpcforum, ale również wśród obcokrajowców ;)

**Comment by TheMolkaPL** [comment]
Ale też nikt nie ma pomysłów na rozwijanie pluginu. Nikt nie ma pomysłów na nowe możliwości. ;)

**Comment by Dzikoysk** [comment]
Nikomu się nie chce tego kontynuować!

**Comment by Wruczek** [comment]
Tak, to chyba jest właśnie największy problem.

**Comment by Dzikoysk** [comment]
Zresztą jak ostatnio patrzyłem, to przecież wyszedł jakiś nowy plugin na gildie na 1.8

**Comment by SlimaKCoder** [comment]
Daj namiary w takim razie ;)

**Comment by TheMolkaPL** [comment]
@SlimaKCoder zobacz [to](https://github.com/xVacuum/qGuilds).

**Comment by SlimaKCoder** [comment]
Bullshit, a nie plugin na gildie. Same podstawowe założenia jak widzisz ssą... W ogóle czemu nikt nie korzysta prawidłowo z baz danych SQL, przecież, język i założenia SQL są 1000x razy prostsze od pisania w Javie?

**Comment by xVacuum** [comment]
To ja żyję? Oh. Jednak żyję.
No to ten, tam molka ma rację święta, szczególnie że ja się na bazach SQL nie znam więc ten no ...

Jak znajdę czas to wrócę troszkę do moich publicznych projektów. Szkoła nie radość ...

**Comment by xVacuum** [comment]
+SlimaKCoder no widzisz, dla mnie nie są ;)
Btw. Chyba pójdę na jakiś kurs sqla ;_;

**Comment by TheMolkaPL** [comment]
> W ogóle czemu nikt nie korzysta prawidłowo z baz danych SQL, przecież język i założenia SQL są 1000x razy prostsze od pisania w Javie?

No jest prosty, ale załadowanie wszystkie w dwie listy przy starcie pluginu już dużo wygodniejsze niż każdorazowe wykonywanie zapytania i asynchroniczne oczekiwanie na odpowiedź(zi).

> Btw. Chyba pójdę na jakiś kurs sqla ;_;

Do SQL nie potrzeba żadnych kursów. Te zasady są takie proste, że wystarczy przeczytać w necie jakiś jeden dobry artykuł na ten temat.

**Comment by SlimaKCoder** [comment]
Właściwie to każdy robi sobie, może byśmy tak połączyli siły i stworzyli jeden konkretny plugin na gildie z porządnym webendem WWW ;)

**Comment by TheMolkaPL** [comment]
No to najwygodniej użyć chyba FunnyGuilds, tylko bazę unowocześnić.

**Comment by xVacuum** [comment]
@SlimaKCoder @TheMolkaPL też mogę wrzucić parę groszy.


o ile mnie chcecie :c

**Comment by Dzikoysk** [comment]
Emmm.... polecałbym użyć wersji 4.0. Po pierwsze - tam nie ma praktycznie żadnego zapisu, a po drugie idea nadal wydaje mi się w sumie dobra (o ile dobrze pamiętam), tylko na koniec warto wywalić refleksje od pobierania fieldów

**Comment by Dzikoysk** [comment]
Ammm... i ten - obowiązkowo implementacja pandy!

**Comment by SlimaKCoder** [comment]
@Dzikoysk skoro bardzo chcesz fotkę tego czarno-białego zwierzaka czczonego w chinach to czemu nie, może być nawet w logo. A plugin nazywał się będzie PandaGuilds ;D

**Comment by Dzikoysk** [comment]
Oooo... to jest cudowny pomysł na nazwę! https://github.com/Panda-Programming-Language/Panda musi być i tyle, chociażby ze względu na szybsze od yamla pliczki cfg :3

**Comment by ZielonyKapturnik** [comment]
To moze ja dodam sklep sms (microsms/paypall/profitsms) oraz moge dac serwer testowy (serwer dopiero za miesiac bo w moto wir w baku a do pracy trzeba jakos dojechac )

**Comment by Wruczek** [comment]
Ja mogę dać hosting WWW opłacony na rok :P

**Comment by Dzikoysk** [comment]
A donejtów, to nikt nie daje

**Comment by ZielonyKapturnik** [comment]
I panowie mam zajebisty pomysl na statystyki aby sygnaturki robilo kd itp ale to trzeba biblioteke gd a nie ogarniam jej konfifuracji.

Dziku moge ci dac w donejcie kosiarke albo wkretarke makity jak chcesz :D

**Comment by SlimaKCoder** [comment]
@ZielonyKapturnik możesz mi to po polsku wyjaśnić? A co do sklepu to mam zamiar takowy implementować, chcesz pomóc?

**Comment by ZielonyKapturnik** [comment]
Slimak zlecilem napisanie takiego bo jestem zbyt leniwy :) jak dostane kod to ci podesle. A co do sygnaturek to ze masz obrazek jakis tam i dynamicznie narzuca ci statystyki na niego

**Comment by SlimaKCoder** [comment]
Ale dla WWW czy w pluginie ta sygnaturka?

**Comment by ZielonyKapturnik** [comment]
Www

**Comment by Dzikoysk** [comment]
Nie ma pluginu, a już sygantury robią!

**Comment by SlimaKCoder** [comment]
To easy, po co Ci do tego GD? I w ogóle zdajesz sobie sprawę, że wiele hostingów nie ma GD, więc będzie wielki zgrzyt od ludu, który miałby tego używać?

**Comment by ZielonyKapturnik** [comment]
Chyba ze masz jakis inny pomysl. Wiem ze przy pomocy gd latwo zrobic cache aby uniknac ataku layer7

**Comment by Wruczek** [comment]
Pierw potrzeba ekipę i pomysł, potem jakieś sygnaturki.

2015-10-05 19:41 GMT+02:00 ZielonyKapturnik <notifications@github.com>:

**Comment by SlimaKCoder** [comment]
GD chroni przed layer 7? Wat? Przecież jak będzie ciągle pytać o obrazki to tak czy siak samo GD nic nie da. GD stworzy obrazek i zapisze do cache, ale przy każdej zmianie będzie tworzyć nowy obrazek. Do tego layer 7 może Cię męczyć bez względu na to jak powstaje obrazek i gdzie go kaszujesz. Jedyna ochrona to limity.

**Comment by SlimaKCoder** [comment]
@Wruczek 

Pomysły mam. Bazę danych i zapytania mogę Wam przygotować, ale nie znam na tyle Javy by to samemu napisać.

**Comment by Wruczek** [comment]
@SlimaKCoder chodzi o cache obrazku...
Generujesz obraz np. raz na pięć minut i zapisujesz go w np. bazie danych.
Jeśli ktoś poprosi o obrazek zwracasz mu zawsze to co masz w bazie, więc nie trzeba za każdym razem pobierać nowych danych i generować nowego obrazka.

**Comment by SlimaKCoder** [comment]
@Wruczek ty chyba nie rozumiesz jak działa atak Layer 7, bez różnicy, gdzie są zasoby na serwerze. Atak ten generuje tyle zapytań, że przeciąża albo serwer, albo łącze... Do tego bredzisz mi tu o zapisywaniu OBRAZKÓW do bazy, od kiedy do cholery zapisuje się całe obrazki do bazy danych?

**Comment by SlimaKCoder** [comment]
@Wruczek 

Polecam poczytać: http://ddosattackprotection.org/blog/layer-7-ddos-attack/ Ani słowa tu nie ma o kaszowaniu. To atak na zupełnie innym poziomie niż myślisz, więc to czy używasz GD i cache czy nie, de fakto nie ma dla niego dużego znaczenia.

**Comment by Wruczek** [comment]
@SlimaKCoder 

> Do tego bredzisz mi tu o zapisywaniu OBRAZKÓW do bazy, od kiedy do cholery zapisuje się całe obrazki do bazy danych?

Spokojnie, to przykład. I tak to Ty najlepiej znasz się tutaj na bazach danych :P

> Polecam poczytać

Ok, zerknę.

No to chyba pozostają tylko limity?

**Comment by ZielonyKapturnik** [comment]
Bardziej mi chodziło oto abyrefresh był obrazka co dany czas w configu żeby myśl nie wysyłać bo dzieci innego ataku nie potrafią zrobić bi trzeba pomyśleć

**Comment by ZielonyKapturnik** [comment]
Wiem jak działało to na manewrach ts3 i jak fajnie serwery padały :D

**Comment by ZielonyKapturnik** [comment]
Banerach (sory za błędy telefon i slownik)

**Comment by SlimaKCoder** [comment]
@Wruczek 
Nie wiem czy z Nas tutaj najlepiej się znam na bazach danych, ale i tak niewiele wiem, jeżeli miałbym się porównywać do zagranicznych programistów.

A co do Layer 7 to tak jak mówiłem na początku, trzeba limitować wszystko (np. za pomocą iptables, ale również są także różnorakie moduły dla serwerów WWW (np. dla Nginx) by limitować konkretne pliki i foldery, etc.

**Comment by SlimaKCoder** [comment]
@ZielonyKapturnik 
Może to strasznie głupi pomysł, taki totalnie wyssany z palca i w ogóle kmiot, ale... czemu by nie pobierać normalnie miniaturek z jakiegoś zewnętrznego API (nie obciąża wtedy twojego serwera pobieraniem) i na to nakładać napisy przy pomocy CSS ("relative positioning") i ewentualnie przy pomocy JavaScript to aktualizować informacje synchronicznie co jakiś (bez odświeżania strony)?

**Comment by ZielonyKapturnik** [comment]
Takie sobie trafi się jakiś debil i będzie płakał że jakby było własne api to by było 13ms szybciej

**Comment by ZielonyKapturnik** [comment]
Wyjdzie w praniu. Jak aktualnie mam pc tylko w pracy i kamerę za plecami więc narazie z telefonu i tabletu mało zrobię. Na mnie trzeba będzie poczekać. A tak btw to dodajmy jeszcze gildijnego jacpota bo tego jeszcze nie było

**Comment by TheMolkaPL** [comment]
@ZielonyKapturnik
> A tak btw to dodajmy jeszcze gildijnego jacpota bo tego jeszcze nie było

Możesz jakiśniej?

**Comment by SlimaKCoder** [comment]
Dobra to może zacznijmy od jakiś założeń. Na początek napiszcie mi jakie dane chcecie zapisywać dla pluginu. Dosłownie wszystko co będziecie zapisywać (po za konfiguracją .yml w plikach oczywiście).

**Comment by Dzikoysk** [comment]
Czekaj, czekaj - jeszcze nikt konkretnie chyba nie powiedział, że będzie to pisał xD

Na pewno muszą być zapisywane fieldy z passVariable:
* https://github.com/Dzikoysk/FunnyGuilds/blob/master/src/net/dzikoysk/funnyguilds/basic/User.java
* https://github.com/Dzikoysk/FunnyGuilds/blob/master/src/net/dzikoysk/funnyguilds/basic/Guild.java
* https://github.com/Dzikoysk/FunnyGuilds/blob/master/src/net/dzikoysk/funnyguilds/basic/Region.java

**Comment by TheMolkaPL** [comment]
A gdyby tak wszystko zapisywać do [JSON przez Gson](http://www.mkyong.com/java/how-do-convert-java-object-to-from-json-format-gson-api/)? Zapis i odczyt jest szybki i prosty. Gorzej z ewentualnym wyszukiwaniem danych.

**Comment by SlimaKCoder** [comment]
Przy dużej ilości powiązanych danych lepsze są bazy danych, to fakt i do tego zostały stworzone. Nawet jeżeli odczyt z plików jest szybszy to wyszukiwanie i łączenie danych ssie po całej lini. Jak na mój gust najlepiej użyć bardzo popularnego MySQL i ewentualnie dać możliwość zapisu do jedno-plikowej bazy danych SQLite (język SQL ten sam tylko trochę inaczej się łączy).

**Comment by TheMolkaPL** [comment]
Chodzi mi o SQL, ale dane w komórkach zapisywać przez JSON.

**Comment by SlimaKCoder** [comment]
@TheMolkaPL Poproszę jakoś jaśniej i konkretniej, najlepiej na przykładzie.

**Comment by SlimaKCoder** [comment]
@Wruczek @TheMolkaPL @xVacuum @ZielonyKapturnik @Dzikoysk 
Taki kurs mi wystarczy (+ API Spigota i Bukkita oczywiście)? http://kenis.pl/kurs,kurs-programowana-w-jezyku-java-od-podstaw,11517

**Comment by TheMolkaPL** [comment]
Przykładowo mamy tabelę graczy

```
----------------------------------------------------------------------------------------------------------------------------------------
|                 UUID                 |                                            Wartość                                            |
----------------------------------------------------------------------------------------------------------------------------------------
| 2b5f34f6-fb05-4852-a86c-2e03bccbdf89 | [{"name": "TheMolkaPL", "points": "12345"}, "guild": "a580d7a8-b886-4dda-aed6-91d2d9bec8be"]  |
----------------------------------------------------------------------------------------------------------------------------------------
```

JSON wygenerowany przez Gson, który sam pobiera wszystkie zmienne w klasie i tworzy z nich jedną wielką mapę JSON.

Dodatkowo unikalnym ID gildii zrobiłbym UUID z tego powodu, żeby kiedyś ewentualnie wprowadzić możliwość zmiany jej tagu.

**Comment by Wruczek** [comment]
@SlimaKCoder Kurs wygląda ok. Jeśli chodzi o API to polecam [tego gościa](https://www.youtube.com/user/PogoStick29Dev/).

Serie na jego kanale:
- [Bukkit Coding Remastered](https://www.youtube.com/watch?v=6oxSss8RJWo&list=PLAF3anQEEkzTLCcGBOsA5BxNY3pIbvoUE) - odnowiona seria Bukkit Coding, zacznij do tego
- [Bukkit Coding](https://www.youtube.com/watch?v=HlrMN06wW7U&index=4&list=PLAF3anQEEkzREsHA8yZzVhc3_GHcPnqxR) - stara seria, zawiera jednak ponad 80 filmów, a w API prawie nic się nie zmieniło więc spokojnie możesz się z tego uczyć


Alternatywnie możesz zobaczyć także [TheBCBroz](https://www.youtube.com/channel/UCOBqSqnLO7Z42Y8JwgfhpRQ).

**Comment by xVacuum** [comment]
@SlimaKCoder no kurs nawet okej. Podstawy zawsze spoko, sam może sobie poczytam niektóre rzeczy :P  

@TheMolkaPL ty mi lepiej podlinkuj gdzie się nauczę trochę o mysql w javie k?

**Comment by SlimaKCoder** [comment]
@TheMolkaPL Yyyy... widzę, że nie wiesz jakie są zalety i do czego w ogóle służy baza danych... ale objaśnię Ci w telegraficznym skrócie. W bazie danych dane rozbija się na najmniejsze cząstkowe dane i zapisuje się je w odpowiednich kolumnach (z odpowiednim typem). W jednej tabeli są dane na temat jednego rodzaju obiektów istniejących w rzeczywistości. Czyli tabela "uczniowie" zawiera informacje o prawdziwych uczniach, etc. Po co? Dane są rozbite by ułatwić wyszukiwanie i grupowanie ich. Dla przykładu wypisanie wszystkich imion uczniów z bazy danych (do np. tablicy) sprowadza się do prostego zapytania "SELECT imie FROM uczniowie" i tyle. Nic więcej nie pobiera, a czas zapytania jest bardzo krótki. Gdybyś chciał to samo zrobić używając JSON i MySQL musiałbyś pobrać WSZYSTKIE DANE, potem je odkodować z JSON i dopiero wypisać same imiona (np. też do tablicy). Dodatkowo baza danych pozwala na referencje i klucze obce. Dzięki nim można tworzyć obiekty zależne. Czyli np. wiemy, że każdy uczeń ma klasę, ale każda klasa ma jakąś określoną salę i wychowawcę. Dlatego przy w tabeli "uczniowie" dla każdego ucznia napiszemy jaką ma klasę (najlepiej przy pomocy unikalnego id), a potem znając identyfikator odszukamy w innej tabeli o nazwie "klasy" szczegółowe informacje o tejże klasie. Tak to w skrócie działa, ale baza danych ma o wiele więcej możliwości i zalet.

**Comment by SlimaKCoder** [comment]
Model bazy danych wedle mnie (pseudokod):
```yml
// Standardowo prefix będzie do ustawienia w konfiguracji bazy danych
"prefix_users":
- user_id [int, not null, autoincrement, primary key],
- uuid [char(36), unique, not null],
- name [char(16), not null],
- kills [int, default 0],
- deaths [int, default 0],
- points [int, default 0],
- lastAttacker_id [int, foreign key],
- lastVictim_id [int, foreign key],
- guild_id [int, foreign key]

"prefix_guilds":
- guild_id [int, not null, autoincrement, primary key],
- desc [text],
- friendly_fire [bool, default false],
- born [datetimez],
- owner_id [int, unique, not null, foreign key],
- region_id [int, unique, foreign key]

"prefix_guild_homes":
- guild_id [int, not null, primary key, foregin key],
- x [int, not null],
- y [int, not null],
- z [int, not null]

/* W tym modelu jedna gildia może uznawać drugą za wroga,
a ta druga może uznać tą pierwszą za neutralną czy nawet przyjacielską. */
"prefix_guild_relations":
- applicant_id [int, not null, foregin key],
- receiver_id [int, not null, foregin key],
- relation [bool, not null, gdzie 0 = enemy, 1 = friend]
```

Cały czas poprawiam, jak skończę to napisze @End

**Comment by TheMolkaPL** [comment]
Ja to wszystko wiem, ale byłoby szybsze do napisania. Pobieranie można by rozwiązać poprzez zapytanie `LIKE`.

Do Twojej propozycji mam kilka zastrzeżeń.
* Przy zapisie UUID graczy użyłbym `CHAR(36)`, zamiast `VARCHAR` z tego względu, że jest szybszy, a jak wiadomo długość UUID jest niezmienna.
* Nicki graczy zapisywałbym w oddzielnej tabeli, gdzie nigdy by nie były one usuwane. Ułatwiłoby to podgląd graczy w gildii dodając komendę wyświetlającą historię zmiany nicków.
* kille/deady zliczałbym także w oddzielnej tabeli, gdzie każdy rekord do jedna śmierć. Ich ilość byłaby zliczana przez ilość rekordów w bazie. Będzie to dobre przy pobieraniu historii śmierci i zabójstw.
* Blokowanie i odblokowywanie gildii zrobiłbym w oddzielnej tabeli, gdzie także byłaby historia takich blokowań.
* Do regionów dodałbym `INT` jako `PRIMARY KEY` i `AUTO INCREMENT`, po to, aby w przyszłości była możliwość dodania obsługi wielu regionów dla jednej gildii. Dodałbym także kolumnę z nazwą własną takiego regionu. Byłoby to ułatwienie dla graczy w identyfikacji regionów (jeżeli byłoby ich więcej). Domyślne można by ustawić to na `DEFAULT` (patrz drugi punkt niżej);
* Świat w tabeli regionów i domów zapisywałbym po jego UUID (każdy świat ma własne UUID w pliku `uid.dat` w swoim folderze). Baza działałaby wtedy szybciej, a ewentualna zmiana nazwy świata nie zniszczyłaby gildii.
* W tabeli domów dodałbym kolumnę z zapisem nazwy regionu.
* W tabeli relacji dodałbym kolumnę z czasem zawarcia sojuszu/wroga oraz czas rozwiązania. Stworzyłoby to historię w bazie wszystkich wojen i sojuszów. A gdyby tak stworzyć na stronie WWW wielką mapę wojen i sojuszów na tej podstawie? xD

**Comment by SlimaKCoder** [comment]
Wersja bazy danych uwzględniająca poprawki od @TheMolkaPL.
```yml
// Standardowo prefix będzie do ustawienia w konfiguracji bazy danych
"prefix_users":
- user_id [int, not null, autoincrement, primary key],
- uuid [char(36), unique, not null],
- points [int, default 0],
- lastAttacker_id [int, foreign key, null],
- lastVictim_id [int, foreign key, null],
- guild_id [int, foreign key, null]

// Logowanie nicków
"prefix_users_names":
- log_id [int, not null, autoincrement,  primary key],
- user_id [int, not null, foreign key],
- name [varchar(16), not null]

// Logowanie zabójstw i śmierci
- log_id [int, not null, autoincrement,  primary key],
- killer_id [int, not null, foreign key],
- victim_id [int, not null, foreign key],
- time [datetime, not null]

"prefix_guilds":
- guild_id [int, not null, autoincrement, primary key],
- tag [varchar(30), not null],
- desc [text, null],
// Domyślna wartość żyć powinna być zmienna w konfiguracji.
- lives [smallint, default 5],
- friendlyFire [bool, default false],
- born [datetime, not null],
- isValidated [bool, default false],
- owner_id [int, unique, not null, foreign key],

// Historia blokowania gildii
- lock_id [int, not null, autoincrement, primary key],
- lockReason [text, null],
- assigned [datetime, not null],
- expires [datetime, null]

// Każda gildia ma jeden region by nie zapychać bazy.
// Nie każda gildia musi mieć region.
"prefix_guilds_regions":
- region_id [int, not null, autoincrement, primary key],
- regionName [varchar(30), null],
- guild_id [int, not null, foregin key],
- centerX [int, not null],
- centerZ [int, not null],
- size [int, not null],
- world [char(36), null]

// Osobna tabela dla homów, szybciej będzie znajdywać miejsce
// teleportacji, bo nie każda gildia musi mieć home.
// Home można ustawiać niezależnie od regionu.
"prefix_guilds_homes":
- guild_id [int, not null, foregin key, primary key],
- homeName [varchar(30), null],
- homeX [int, not null],
- homeY [int, not null],
- homeZ [int, not null],
- world [char(36), null]

// W tym modelu jedna gildia może uznawać drugą za wroga,
// a ta druga może uznać tą pierwszą za neutralną czy nawet przyjacielską.
"prefix_guilds_relations":
- applicant_id [int, not null, foregin key, part of primary key],
- receiver_id [int, not null, foregin key, part of primary key],
- relation [bool, gdzie 0 = rival, 1 = friend],
- expires  [datetime, null]

// Proces podbijania gildii, czyli odblokowania jej regionu.
"prefix_guilds_conquests":
- attacker_id [int, not null, foregin key, part of primary key],
- defender_id [int, not null, foregin key, part of primary key],
- startDate [datetime, not null],
- endDate [datetime, null],
// Progres wyliczany na podstawie punktów za zabicia i zgony podczas wojny.
- progress [int(10000), default 0]
```

I jak się podoba?
